export const APP_NAME = '极享AI';
export const APP_FULL_NAME = '极享AI — 内部管理系统';

export const ROUTE_TITLES: Record<string, string> = {
  '/dashboard': '数据驾驶舱',
  '/products': '产品矩阵中心',
  '/project/overview': '项目总览',
  '/project/faq': 'FAQ管理',
  '/project/competitive': '竞品对比',
  '/project/guide': '新人指南',
  '/sales/scripts': '话术库',
  '/sales/qa': '百问百答',
  '/sales/diagnosis': '客户诊断',
  '/sales/quotations': '报价方案',
  '/sales/sop': '升单SOP',
  '/agent/list': '代理商列表',
  '/agent/policies': '政策管理',
  '/agent/agreements': '代理协议',
  '/agent/settlements': '佣金结算',
  '/agent/growth': '成长路径',
  '/acquisition/daily': '每日动作',
  '/acquisition/short-video': '短视频获客',
  '/acquisition/live': '直播获客',
  '/acquisition/private-domain': '私域运营',
  '/acquisition/offline': '地推管理',
  '/cases/list': '案例库',
  '/cases/templates': '案例模板',
  '/cases/materials': '素材收集',
  '/cases/interviews': '客户采访',
  '/training/courses': '课程中心',
  '/training/camps': '训练营',
  '/training/assignments': '学员作业',
  '/training/progress': '进度追踪',
  '/delivery/sop': 'SOP管理',
  '/delivery/acceptance': '验收标准',
  '/delivery/diagnosis': '服务诊断',
  '/delivery/after-sale': '售后服务',
  '/policies/pricing': '定价策略',
  '/policies/commission': '佣金政策',
  '/policies/refund': '退款政策',
  '/policies/compliance': '合规管理',
  '/policies/contracts': '合同模板',
  '/brand/vi': 'VI规范',
  '/brand/templates': '品牌模板',
  '/brand/certificates': '品牌证书',
  '/data/dashboard': '运营看板',
  '/data/funnel': '数据漏斗',
  '/data/ranking': '排名榜',
  '/data/complaint': '投诉分析',
  '/data/reviews': '运营复盘',
  '/materials/scripts': '短视频脚本',
  '/materials/live-scripts': '直播话术',
  '/materials/moments': '朋友圈素材',
  '/materials/posters': '海报素材',
  '/materials/videos': '视频素材',
  '/delivery/survey': '客户调研',
  '/policies/reporting': '客户报备',
  '/settings/users': '用户管理',
  '/settings/roles': '角色管理',
  '/settings/logs': '操作日志',
};

export const PHASE_LABELS = {
  '1A': '首批上线',
  '1B': '第二批上线',
  '2': '后续规划',
} as const;
